### ISSUE TITLE
Main Menu loading crash/freeze.

### ISSUE THREAD

**Issue by Asellia** [Kapps/PoEUncrasher#1]
Idk if its normal, but I get the issue before main menu, that first 'grinding gear' before you 'login'. Could it be adjusted to help during that sort of menu, and pre-char select, too?

**Comment by CrimsonGhost69** [comment]
+1 

would be better if it starts with pausedCores

**Comment by Kapps** [comment]
Done, the new version (https://github.com/Kapps/PoEUncrasher/releases/tag/v1.1.0) will park cores on startup.
