### ISSUE TITLE
Doesn't work with Intel i7 11700K

### ISSUE THREAD

**Issue by CrimsonGhost69** [Kapps/PoEUncrasher#2]
It doesn't work with Intel i7 11700K. Other affinity bitmask? 

I changed the code to direct start with parked Cores but it still freezes completely

**Comment by Dusre** [comment]
I made these changes for my i7 6700k and didnt have any crashes with these affinitys.  I think the problem is with the hyperthreading "cores".
`    var affinityBits = new StringBuilder(new string('1', Environment.ProcessorCount))
    {
        [^2] = '0',
        [^4] = '0',
        [^6] = '0',
        [^8] = '0',
    };`

**Comment by CrimsonGhost69** [comment]
Ich changed it, but the game still freezes and it takes around 2 mins for Windows to show a prompt that i can kill the process. At least you don't have to hard reset your PC but Game performance overall is worse than ever. thank you nonetheless.

**Comment by Kapps** [comment]
Try out the new version. You'll have to run it as an Administrator, but I believe I found a fix to be able to unfreeze PoE when it freezes.
