### ISSUE TITLE
Can't download / use due to MS Windows Defender warning

### ISSUE THREAD

**Issue by ErdbeerGott** [Kapps/PoEUncrasher#4]
Detected: Trojan:Win32/Wacatac.H!ml

webfile: C:\Users\Admin\Downloads\PoEUncrasher.zip|https://objects.githubusercontent.com/github-production-release-asset-2e65be/905002104/26543ed1-c49b-4e6a-a8db-7dbdcd3038c6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241219%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241219T121935Z&X-Amz-Expires=300&X-Amz-Signature=5165d5073e1d46daca738cad5e3fecf9b41f87e2298f01f05b0b6424965f1a90&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3DPoEUncrasher.zip&response-content-type=application%2Foctet-stream|

**Comment by CrimsonGhost69** [comment]
The source code is open source. You could ask ChatGPT what the code does. But let me tell you it is a false positive. The Script is chaging CPU affinity for the PoE Process, probably that's why it's detecting some stuff. The Program is safe to use.

**Comment by Breadwinka** [comment]
Yup program is scanning the log file checking for entries related to loading then parks your cpu cores, if POE2 goes unresponsive then changes priority to real time, once loading finishes it unparks them and sets back to normal priority. Definitely a false positive. https://www.virustotal.com/gui/file/be42db7621cbe5f2ba92369fcf07ee67d8f064a802ddef5f1068053959ee4665

**Comment by ErdbeerGott** [comment]
Thanks for the feedback - it's working!
