### ISSUE TITLE
Can't run .exe

### ISSUE THREAD

**Issue by sgriosadair** [Kapps/PoEUncrasher#7]
Thanks for making this for the community! 

Sadly, I have a problem where I can't use the .exe at all. When trying to run it I get the SmartScreen warning on the first attempt but nothing comes up after choosing Run Anyways. Any subsequent attempt to run the program results in a brief flash of a window which closes immediately then nothing.

I have .NET 9 installed, no virus scan/protection issues preventing the program from running.

**Comment by Kapps** [comment]
A few suggestions:
- Make sure you're not running it from the zip file.
- Make sure you have the x64 version of .NET 9 installed (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-9.0.101-windows-x64-installer)
- If it still doesn't work, you can try running it from a command prompt (open up cmd and cd into the right folder, then run it from there). Hopefully it should then give a more useful error.

**Comment by sgriosadair** [comment]
Hey thanks, Kapps. I should have known better... I installed the .NET 9 Core instead of the SDK.

After installing the correct .NET required it now runs as expected. Sorry for the PEBKAC error. lol

Again, thanks for taking the time to help. All good here and I really appreciate it!
